"""Initial migration

Revision ID: 3df46d3adc5b
Revises: 
Create Date: 2026-01-07 04:02:44.307754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3df46d3adc5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('books_genre_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('books_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'authors', ['author_id'], ['author_id'])
        batch_op.create_foreign_key(None, 'genres', ['genre_id'], ['genre_id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_items_order_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('order_items_book_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['book_id'])
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['order_id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='order_status'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::order_status"))
        batch_op.drop_constraint(batch_op.f('orders_customer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['customer_id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=postgresql.ENUM('credit_card', 'debit_card', 'paypal', 'bank_transfer', 'other', name='payment_method_type'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_provider_payment_id'))
        batch_op.drop_constraint(batch_op.f('payments_order_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['order_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('manager', 'sales', 'supply', 'finance', name='user_role'),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('manager', 'sales', 'supply', 'finance', name='user_role'),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_order_id_fkey'), 'orders', ['order_id'], ['order_id'], ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_provider_payment_id'), ['provider_payment_id'], unique=False)
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('credit_card', 'debit_card', 'paypal', 'bank_transfer', 'other', name='payment_method_type'),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_customer_id_fkey'), 'customers', ['customer_id'], ['customer_id'], ondelete='CASCADE')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='order_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::order_status"))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_items_book_id_fkey'), 'books', ['book_id'], ['book_id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('order_items_order_id_fkey'), 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('books_author_id_fkey'), 'authors', ['author_id'], ['author_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('books_genre_id_fkey'), 'genres', ['genre_id'], ['genre_id'], ondelete='RESTRICT')

    # ### end Alembic commands ###
